channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - affine=2.3.0=py_0
  - aiohttp=3.6.1=py37h516909a_0
  - alembic=1.1.0=py_0
  - asn1crypto=0.24.0=py37_1003
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - blinker=1.4=py_1
  - bokeh=1.3.4=py37_0
  - boost-cpp=1.70.0=h8e57a91_2
  - boto3=1.9.253=py_0
  - botocore=1.12.253=py_0
  - bzip2=1.0.8=h516909a_1
  - ca-certificates=2019.9.11=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.9.11=py37_0
  - certipy=0.1.3=py_0
  - cffi=1.12.3=py37h8022711_0
  - cfitsio=3.470=hb60a0a2_2
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=1.2.2=py_0
  - colorcet=2.0.1=py_0
  - configurable-http-proxy=1.3.0=0
  - cryptography=2.7=py37h72c5cf5_0
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.0=py37h516909a_0
  - dask=2.6.0=py_0
  - dask-core=2.6.0=py_0
  - datashader=0.8.0=py_0
  - datashape=0.5.4=py_1
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - distributed=2.6.0=py_0
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=he1b5a44_1004
  - fiona=1.8.9.post2=py37hdff7cfa_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - freexl=1.0.5=h14c3975_1002
  - fsspec=0.5.2=py_0
  - gdal=2.4.2=py37h5f563d9_4
  - geopandas=0.6.1=py_1
  - geos=3.7.2=he1b5a44_2
  - geotiff=1.5.1=h560c3f3_2
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.7=h516909a_1
  - glib=2.58.3=h6f030ca_1002
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - heapdict=1.0.1=py_0
  - holoviews=1.12.6=py_0
  - hvplot=0.5.2=py_0
  - icu=64.2=he1b5a44_1
  - idna=2.8=py37_1000
  - imageio=2.6.1=py37_0
  - ipykernel=5.1.2=py37h5ca1d4c_0
  - ipython=7.8.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.1=py_0
  - jmespath=0.9.4=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - json5=0.8.5=py_0
  - jsonschema=3.0.2=py37_0
  - jupyter-server-proxy=1.1.0=py_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.4.0=py_0
  - jupyterhub=1.0.0=py37_0
  - jupyterlab=1.1.4=py_0
  - jupyterlab_server=1.0.6=py_0
  - kealib=1.4.10=h58c409b_1005
  - kiwisolver=1.1.0=py37hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.65.3=hda55be3_0
  - libdap4=3.20.4=hd3bb157_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=2.4.2=hbef8c27_4
  - libgfortran-ng=7.3.0=hdf63c60_2
  - libiconv=1.15=h516909a_1005
  - libkml=1.3.0=h4fcabce_1010
  - liblapack=3.8.0=14_openblas
  - libllvm8=8.0.1=hc9558a2_0
  - libnetcdf=4.6.2=h303dfb8_1003
  - libopenblas=0.3.7=h6e990d7_2
  - libpng=1.6.37=hed695b0_0
  - libpq=11.5=hd9ab2ff_1
  - libsodium=1.0.17=h516909a_0
  - libspatialindex
  - libspatialite=4.3.0a=he1bb1e1_1029
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=hfc65ed5_1004
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.32.0=h516909a_0
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hee79883_5
  - llvmlite=0.30.0=py37h8b12597_0
  - locket=0.2.0=py_2
  - lz4-c=1.8.3=he1b5a44_1001
  - mako=1.1.0=py_0
  - markdown=3.1.1=py_0
  - markupsafe=1.1.1=py37h14c3975_0
  - matplotlib-base=3.1.1=py37he7580a8_1
  - mistune=0.8.4=py37h14c3975_1000
  - msgpack-python=0.6.2=py37hc9558a2_0
  - multidict=4.5.2=py37h14c3975_1000
  - multipledispatch=0.6.0=py_0
  - munch=2.4.0=py_0
  - nbconvert=5.4.1=py_2
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_0
  - nodejs=12.11.1=h10a4023_0
  - notebook=5.7.8=py37_1
  - nteract_on_jupyter=2.1.3=py_0
  - numba=0.46.0=py37hb3f55d8_0
  - numpy=1.17.3=py37h95a1406_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h21c5421_1
  - openssl=1.1.1c=h516909a_0
  - packaging=19.2=py_0
  - pamela=1.0.0=py_0
  - pandas=0.25.2=py37hb3f55d8_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - panel=0.6.4=0
  - param=1.9.2=py_0
  - parso=0.5.1=py_0
  - partd=1.0.0=py_0
  - pcre=8.43=he1b5a44_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pillow=6.2.1=py37h6b7be26_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - poppler=0.67.0=ha967d66_7
  - poppler-data=0.4.9=1
  - postgresql=11.5=hc63931a_1
  - proj4=6.1.0=he751ad9_2
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - psutil=5.6.3=py37h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.19=py37_1
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pycurl=7.43.0.2=py37h16ce93b_1
  - pygments=2.4.2=py_0
  - pyjwt=1.7.1=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyproj=2.2.1=py37hc44880f_0
  - pyrsistent=0.15.4=py37h516909a_0
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h33d41f4_1
  - python-dateutil=2.8.0=py_0
  - python-editor=1.0.4=py_0
  - pytz=2019.3=py_0
  - pyviz_comms=0.7.2=py_0
  - pywavelets=1.1.1=py37hc1659b7_0
  - pyyaml=5.1.2=py37h516909a_0
  - pyzmq=18.1.0=py37h1768529_0
  - rasterio=1.0.28=py37hdff7cfa_1
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py37_1
  - rtree=0.8.3=py37h666c49c_1002
  - s3transfer=0.2.1=py37_0
  - scikit-image=0.16.2=py37hb3f55d8_0
  - scipy=1.3.1=py37h921218d_2
  - send2trash=1.5.0=py_0
  - setuptools=41.2.0=py37_0
  - shapely=1.6.4=py37hec07ddf_1006
  - simpervisor=0.3=py_1
  - six=1.12.0=py37_1000
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.1.0=py_0
  - sqlalchemy=1.3.8=py37h516909a_0
  - sqlite=3.29.0=hcee41ef_1
  - tblib=1.4.0=py_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=hed695b0_1003
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h516909a_0
  - traitlets=4.3.2=py37_1000
  - tzcode=2019a=h516909a_1002
  - urllib3=1.25.3=py37_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.4.2=py37_1000
  - xarray=0.14.0=py_0
  - xerces-c=3.2.2=h8412b87_1004
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - yarl=1.3.0=py37h14c3975_1000
  - zeromq=4.3.2=he1b5a44_2
  - zict=1.0.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.3=h3b9ef0a_0
  - pip:
    - jupyter-panel-proxy==0.1.0
